name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Run Playwright Tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Upload Allure raw results
    - name: Upload Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    # Generate Allure Report (HTML)
    - name: Generate Allure Report # Install allure command globally
      run: |
        npm install -g allure-commandline --save-dev
        allure generate allure-results --clean -o allure-report

    # Upload the generated Allure HTML report
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
